title: Shiv Shankar # your name (or website title) here
logo: "/images/actual_crop.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, I'm Shiv! I am currently an undergraduate at UC Berkeley pursuing degrees in Electrical Engineering & Computer Science and Data Science.
  <br><br>
  I am passionate about crafting creative and meaningful products at the intersection of technology, finance, and people!
  <br><br>
  <a href="https://www.linkedin.com/in/shiv-shankar-991735196/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
